server:
  port: 8084
spring:
  application:
    name: buy_server
  datasource:
    url: jdbc:mysql://localhost:3306/hbq_mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/