server:
  port: 8081
spring:
  application:
    name: user-server
  datasource:
      url: jdbc:mysql://localhost:3306/hbq_mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      password: mysql521
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  check-config-location: true
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: cn.hubaoquan.mall.userservice.mapper

